# Generated by Django 6.0.6 on 2026-06-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacherprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Paper', 'verbose_name_plural': 'Papers'},
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.section', verbose_name='Paper'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='component',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Tutorial', 'Tutorial'), ('Practical', 'Practical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.section', verbose_name='Paper'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'attendance_date')},
        ),
    ]
