# Generated by Django 6.0.6 on 2026-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_studentprofile_address_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
