# Generated by Django 6.0.6 on 2026-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_teachersubject_component_teacherprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_multiple_periods_same_day', models.BooleanField(default=False, help_text='If enabled, multiple attendance entries on the same day by the same teacher for the same paper are counted.')),
            ],
        ),
    ]
